lsi: false
safe: true
incremental: false
highlighter: rouge
github: [metadata]
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"
author:
  name             : "Your Name"
  bio              : "I am an **amazing** person."
  location         : "Somewhere"
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache