lsi: false
safe: true
incremental: false
highlighter: rouge
github: [metadata]
url: "https://www.tomhyluo.com"
repository: "lhy2813419591/tomhyluo.com"
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"
locale: "zh-CN"
atom_feed:
  hide: true
author:
  name             : "tomhyluo"
  bio              : "不忘初心，方得始终"
  location         : "成都"
  avatar           : "/assets/images/avatar.jpg"
  links:
  - label: "Email"
    icon: "fas fa-fw fa-envelope-square"
    url: "mailto:luohaoyu0920@foxmail.com"
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/lhy2813419591"
  - label: "博客园"
    icon: "fas fa-blog"
    url: "https://www.cnblogs.com/lhyxq/"    
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lhy2813419591"    
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      related: true
head_scripts:
  - https://cdnjs.cloudflare.com/ajax/libs/viewerjs/1.11.3/viewer.min.js
  - /assets/js/custom.js 
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache