lsi: false
safe: true
source: lhy2813419591.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"
author:
  name             : "Your Name"
  bio              : "I am an **amazing** person."
  location         : "Somewhere"
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
