lsi: false
safe: true
incremental: false
highlighter: rouge
github: [metadata]
url: "https://www.tomhyluo.com"
repository: "lhy2813419591/tomhyluo.com"
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"
author:
  name             : "tomhyluo"
  bio              : "不忘初心，方得始终"
  location         : "成都"
  avatar           : "/assets/images/avatar.jpg"
  links:
  - label: "Email"
    icon: "fas fa-fw fa-envelope-square"
    url: "mailto:luohaoyu0920@foxmail.com"
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/lhy2813419591"  
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      related: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache